/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as ChainReactionV3ContractJson } from "../ChainReactionV3.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace ChainReactionV3Types {
  export type Fields = {
    factoryId: HexString;
    durationDecreaseMs: bigint;
    minDuration: bigint;
    addrFees: Address;
    isFixedTokenId: boolean;
    chainId: bigint;
    currentEntry: bigint;
    lastPlayer: Address;
    lastEntryTimestamp: bigint;
    pot: bigint;
    boostAmount: bigint;
    playerCount: bigint;
    isActive: boolean;
    baseEntry: bigint;
    endTimestamp: bigint;
    durationMs: bigint;
    multiplierBps: bigint;
    tokenId: HexString;
    burnBps: bigint;
    burnedAmount: bigint;
    feesBps: bigint;
    decayPeriodMs: bigint;
  };

  export type State = ContractState<Fields>;

  export type ChainStartedEvent = ContractEvent<{
    chainId: bigint;
    startBlock: bigint;
    feesBps: bigint;
    tokenId: HexString;
  }>;
  export type PlayerJoinedEvent = ContractEvent<{
    chainId: bigint;
    player: Address;
    entryFee: bigint;
    newPot: bigint;
    position: bigint;
    amountBurned: bigint;
    tokenId: HexString;
  }>;
  export type ChainEndedEvent = ContractEvent<{
    chainId: bigint;
    winner: Address;
    payout: bigint;
    totalBurned: bigint;
    feesAmount: bigint;
  }>;
  export type ChainTimeoutEvent = ContractEvent<{
    chainId: bigint;
    player: Address;
  }>;
  export type PotBoostedEvent = ContractEvent<{
    caller: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    startChain: {
      params: CallContractParams<{
        callerAddr: Address;
        payment: bigint;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        tokenIdGame: HexString;
        burnRate: bigint;
        feesBpsGame: bigint;
        decayPeriodMsGame: bigint;
      }>;
      result: CallContractResult<[bigint, bigint, bigint, bigint]>;
    };
    joinChain: {
      params: CallContractParams<{ callerAddr: Address; payment: bigint }>;
      result: CallContractResult<[bigint, bigint, bigint, bigint, bigint]>;
    };
    endChain: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[bigint, Address, bigint, bigint, bigint]>;
    };
    canEnd: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    getChainInfo: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<
        [bigint, bigint, Address, bigint, bigint, boolean, bigint]
      >;
    };
    incentive: {
      params: CallContractParams<{ callerAddr: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getNextEntryPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getFactoryId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    startChain: {
      params: SignExecuteContractMethodParams<{
        callerAddr: Address;
        payment: bigint;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        tokenIdGame: HexString;
        burnRate: bigint;
        feesBpsGame: bigint;
        decayPeriodMsGame: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    joinChain: {
      params: SignExecuteContractMethodParams<{
        callerAddr: Address;
        payment: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    endChain: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    canEnd: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getChainInfo: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    incentive: {
      params: SignExecuteContractMethodParams<{
        callerAddr: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getNextEntryPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getFactoryId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  ChainReactionV3Instance,
  ChainReactionV3Types.Fields
> {
  encodeFields(fields: ChainReactionV3Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  eventIndex = {
    ChainStarted: 0,
    PlayerJoined: 1,
    ChainEnded: 2,
    ChainTimeout: 3,
    PotBoosted: 4,
  };
  consts = {
    ErrorCodes: {
      ChainNotActive: BigInt("0"),
      InsufficientPayment: BigInt("2"),
      ChainAlreadyActive: BigInt("3"),
      TooEarlyToEnd: BigInt("4"),
      GameEnded: BigInt("5"),
      DurationToLow: BigInt("6"),
      BurnRateTooHigh: BigInt("7"),
      FeesToHigh: BigInt("8"),
      TokenIdIncorrect: BigInt("9"),
      DecayPeriodTooLong: BigInt("10"),
    },
  };

  at(address: string): ChainReactionV3Instance {
    return new ChainReactionV3Instance(address);
  }

  tests = {
    startChain: async (
      params: TestContractParamsWithoutMaps<
        ChainReactionV3Types.Fields,
        {
          callerAddr: Address;
          payment: bigint;
          durationGameMs: bigint;
          multiplierGameBps: bigint;
          tokenIdGame: HexString;
          burnRate: bigint;
          feesBpsGame: bigint;
          decayPeriodMsGame: bigint;
        }
      >
    ): Promise<
      TestContractResultWithoutMaps<[bigint, bigint, bigint, bigint]>
    > => {
      return testMethod(this, "startChain", params, getContractByCodeHash);
    },
    joinChain: async (
      params: TestContractParamsWithoutMaps<
        ChainReactionV3Types.Fields,
        { callerAddr: Address; payment: bigint }
      >
    ): Promise<
      TestContractResultWithoutMaps<[bigint, bigint, bigint, bigint, bigint]>
    > => {
      return testMethod(this, "joinChain", params, getContractByCodeHash);
    },
    endChain: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionV3Types.Fields, never>,
        "args"
      >
    ): Promise<
      TestContractResultWithoutMaps<[bigint, Address, bigint, bigint, bigint]>
    > => {
      return testMethod(this, "endChain", params, getContractByCodeHash);
    },
    canEnd: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionV3Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "canEnd", params, getContractByCodeHash);
    },
    getChainInfo: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionV3Types.Fields, never>,
        "args"
      >
    ): Promise<
      TestContractResultWithoutMaps<
        [bigint, bigint, Address, bigint, bigint, boolean, bigint]
      >
    > => {
      return testMethod(this, "getChainInfo", params, getContractByCodeHash);
    },
    incentive: async (
      params: TestContractParamsWithoutMaps<
        ChainReactionV3Types.Fields,
        { callerAddr: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "incentive", params, getContractByCodeHash);
    },
    getNextEntryPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionV3Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getNextEntryPrice",
        params,
        getContractByCodeHash
      );
    },
    getFactoryId: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionV3Types.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getFactoryId", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: ChainReactionV3Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const ChainReactionV3 = new Factory(
  Contract.fromJson(
    ChainReactionV3ContractJson,
    "",
    "61069fdba1b27971e41e23be8f85c086bb8c12fdd6f2de27ce87bcbbafb824aa",
    types.AllStructs
  )
);
registerContract(ChainReactionV3);

// Use this class to interact with the blockchain
export class ChainReactionV3Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ChainReactionV3Types.State> {
    return fetchContractState(ChainReactionV3, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeChainStartedEvent(
    options: EventSubscribeOptions<ChainReactionV3Types.ChainStartedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReactionV3.contract,
      this,
      options,
      "ChainStarted",
      fromCount
    );
  }

  subscribePlayerJoinedEvent(
    options: EventSubscribeOptions<ChainReactionV3Types.PlayerJoinedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReactionV3.contract,
      this,
      options,
      "PlayerJoined",
      fromCount
    );
  }

  subscribeChainEndedEvent(
    options: EventSubscribeOptions<ChainReactionV3Types.ChainEndedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReactionV3.contract,
      this,
      options,
      "ChainEnded",
      fromCount
    );
  }

  subscribeChainTimeoutEvent(
    options: EventSubscribeOptions<ChainReactionV3Types.ChainTimeoutEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReactionV3.contract,
      this,
      options,
      "ChainTimeout",
      fromCount
    );
  }

  subscribePotBoostedEvent(
    options: EventSubscribeOptions<ChainReactionV3Types.PotBoostedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReactionV3.contract,
      this,
      options,
      "PotBoosted",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | ChainReactionV3Types.ChainStartedEvent
      | ChainReactionV3Types.PlayerJoinedEvent
      | ChainReactionV3Types.ChainEndedEvent
      | ChainReactionV3Types.ChainTimeoutEvent
      | ChainReactionV3Types.PotBoostedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      ChainReactionV3.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    startChain: async (
      params: ChainReactionV3Types.CallMethodParams<"startChain">
    ): Promise<ChainReactionV3Types.CallMethodResult<"startChain">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "startChain",
        params,
        getContractByCodeHash
      );
    },
    joinChain: async (
      params: ChainReactionV3Types.CallMethodParams<"joinChain">
    ): Promise<ChainReactionV3Types.CallMethodResult<"joinChain">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "joinChain",
        params,
        getContractByCodeHash
      );
    },
    endChain: async (
      params?: ChainReactionV3Types.CallMethodParams<"endChain">
    ): Promise<ChainReactionV3Types.CallMethodResult<"endChain">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "endChain",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    canEnd: async (
      params?: ChainReactionV3Types.CallMethodParams<"canEnd">
    ): Promise<ChainReactionV3Types.CallMethodResult<"canEnd">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "canEnd",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getChainInfo: async (
      params?: ChainReactionV3Types.CallMethodParams<"getChainInfo">
    ): Promise<ChainReactionV3Types.CallMethodResult<"getChainInfo">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "getChainInfo",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    incentive: async (
      params: ChainReactionV3Types.CallMethodParams<"incentive">
    ): Promise<ChainReactionV3Types.CallMethodResult<"incentive">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "incentive",
        params,
        getContractByCodeHash
      );
    },
    getNextEntryPrice: async (
      params?: ChainReactionV3Types.CallMethodParams<"getNextEntryPrice">
    ): Promise<ChainReactionV3Types.CallMethodResult<"getNextEntryPrice">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "getNextEntryPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getFactoryId: async (
      params?: ChainReactionV3Types.CallMethodParams<"getFactoryId">
    ): Promise<ChainReactionV3Types.CallMethodResult<"getFactoryId">> => {
      return callMethod(
        ChainReactionV3,
        this,
        "getFactoryId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    startChain: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"startChain">
    ): Promise<ChainReactionV3Types.SignExecuteMethodResult<"startChain">> => {
      return signExecuteMethod(ChainReactionV3, this, "startChain", params);
    },
    joinChain: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"joinChain">
    ): Promise<ChainReactionV3Types.SignExecuteMethodResult<"joinChain">> => {
      return signExecuteMethod(ChainReactionV3, this, "joinChain", params);
    },
    endChain: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"endChain">
    ): Promise<ChainReactionV3Types.SignExecuteMethodResult<"endChain">> => {
      return signExecuteMethod(ChainReactionV3, this, "endChain", params);
    },
    canEnd: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"canEnd">
    ): Promise<ChainReactionV3Types.SignExecuteMethodResult<"canEnd">> => {
      return signExecuteMethod(ChainReactionV3, this, "canEnd", params);
    },
    getChainInfo: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"getChainInfo">
    ): Promise<
      ChainReactionV3Types.SignExecuteMethodResult<"getChainInfo">
    > => {
      return signExecuteMethod(ChainReactionV3, this, "getChainInfo", params);
    },
    incentive: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"incentive">
    ): Promise<ChainReactionV3Types.SignExecuteMethodResult<"incentive">> => {
      return signExecuteMethod(ChainReactionV3, this, "incentive", params);
    },
    getNextEntryPrice: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"getNextEntryPrice">
    ): Promise<
      ChainReactionV3Types.SignExecuteMethodResult<"getNextEntryPrice">
    > => {
      return signExecuteMethod(
        ChainReactionV3,
        this,
        "getNextEntryPrice",
        params
      );
    },
    getFactoryId: async (
      params: ChainReactionV3Types.SignExecuteMethodParams<"getFactoryId">
    ): Promise<
      ChainReactionV3Types.SignExecuteMethodResult<"getFactoryId">
    > => {
      return signExecuteMethod(ChainReactionV3, this, "getFactoryId", params);
    },
  };

  async multicall<Calls extends ChainReactionV3Types.MultiCallParams>(
    calls: Calls
  ): Promise<ChainReactionV3Types.MultiCallResults<Calls>>;
  async multicall<Callss extends ChainReactionV3Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<ChainReactionV3Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | ChainReactionV3Types.MultiCallParams
      | ChainReactionV3Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      ChainReactionV3,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
