/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as ChainReactionContractJson } from "../ChainReaction.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace ChainReactionTypes {
  export type Fields = {
    chainId: bigint;
    currentEntry: bigint;
    lastPlayer: Address;
    lastEntryTimestamp: bigint;
    pot: bigint;
    boostAmount: bigint;
    playerCount: bigint;
    isActive: boolean;
    baseEntry: bigint;
    endTimestamp: bigint;
    durationMs: bigint;
    multiplierBps: bigint;
    tokenId: HexString;
    burnBps: bigint;
    burnedAmount: bigint;
    durationDecreaseMs: bigint;
    minDuration: bigint;
  };

  export type State = ContractState<Fields>;

  export type ChainStartedEvent = ContractEvent<{
    chainId: bigint;
    startBlock: bigint;
  }>;
  export type PlayerJoinedEvent = ContractEvent<{
    chainId: bigint;
    player: Address;
    entryFee: bigint;
    newPot: bigint;
    position: bigint;
    amountBurned: bigint;
  }>;
  export type ChainEndedEvent = ContractEvent<{
    chainId: bigint;
    winner: Address;
    payout: bigint;
    totalBurned: bigint;
  }>;
  export type ChainTimeoutEvent = ContractEvent<{
    chainId: bigint;
    player: Address;
  }>;
  export type PotBoostedEvent = ContractEvent<{
    caller: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    startChain: {
      params: CallContractParams<{
        payment: bigint;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        tokenIdGame: HexString;
        burnRate: bigint;
      }>;
      result: CallContractResult<null>;
    };
    joinChain: {
      params: CallContractParams<{ payment: bigint }>;
      result: CallContractResult<null>;
    };
    endChain: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    canEnd: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    getChainInfo: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<
        [bigint, bigint, Address, bigint, bigint, boolean, bigint]
      >;
    };
    incentive: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    getNextEntryPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    startChain: {
      params: SignExecuteContractMethodParams<{
        payment: bigint;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        tokenIdGame: HexString;
        burnRate: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    joinChain: {
      params: SignExecuteContractMethodParams<{ payment: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    endChain: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    canEnd: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getChainInfo: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    incentive: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getNextEntryPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  ChainReactionInstance,
  ChainReactionTypes.Fields
> {
  encodeFields(fields: ChainReactionTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = {
    ChainStarted: 0,
    PlayerJoined: 1,
    ChainEnded: 2,
    ChainTimeout: 3,
    PotBoosted: 4,
  };
  consts = {
    ErrorCodes: {
      ChainNotActive: BigInt("0"),
      InsufficientPayment: BigInt("2"),
      ChainAlreadyActive: BigInt("3"),
      TooEarlyToEnd: BigInt("4"),
      GameEnded: BigInt("5"),
      DurationToLow: BigInt("6"),
      BurnRateTooHigh: BigInt("7"),
    },
  };

  at(address: string): ChainReactionInstance {
    return new ChainReactionInstance(address);
  }

  tests = {
    startChain: async (
      params: TestContractParamsWithoutMaps<
        ChainReactionTypes.Fields,
        {
          payment: bigint;
          durationGameMs: bigint;
          multiplierGameBps: bigint;
          tokenIdGame: HexString;
          burnRate: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "startChain", params, getContractByCodeHash);
    },
    joinChain: async (
      params: TestContractParamsWithoutMaps<
        ChainReactionTypes.Fields,
        { payment: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "joinChain", params, getContractByCodeHash);
    },
    endChain: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "endChain", params, getContractByCodeHash);
    },
    canEnd: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "canEnd", params, getContractByCodeHash);
    },
    getChainInfo: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionTypes.Fields, never>,
        "args"
      >
    ): Promise<
      TestContractResultWithoutMaps<
        [bigint, bigint, Address, bigint, bigint, boolean, bigint]
      >
    > => {
      return testMethod(this, "getChainInfo", params, getContractByCodeHash);
    },
    incentive: async (
      params: TestContractParamsWithoutMaps<
        ChainReactionTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "incentive", params, getContractByCodeHash);
    },
    getNextEntryPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<ChainReactionTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getNextEntryPrice",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: ChainReactionTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const ChainReaction = new Factory(
  Contract.fromJson(
    ChainReactionContractJson,
    "",
    "5a136385437d46408c62daca51a9521ab8674e8c2702015a7df86f798f5e757e",
    []
  )
);
registerContract(ChainReaction);

// Use this class to interact with the blockchain
export class ChainReactionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ChainReactionTypes.State> {
    return fetchContractState(ChainReaction, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeChainStartedEvent(
    options: EventSubscribeOptions<ChainReactionTypes.ChainStartedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReaction.contract,
      this,
      options,
      "ChainStarted",
      fromCount
    );
  }

  subscribePlayerJoinedEvent(
    options: EventSubscribeOptions<ChainReactionTypes.PlayerJoinedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReaction.contract,
      this,
      options,
      "PlayerJoined",
      fromCount
    );
  }

  subscribeChainEndedEvent(
    options: EventSubscribeOptions<ChainReactionTypes.ChainEndedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReaction.contract,
      this,
      options,
      "ChainEnded",
      fromCount
    );
  }

  subscribeChainTimeoutEvent(
    options: EventSubscribeOptions<ChainReactionTypes.ChainTimeoutEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReaction.contract,
      this,
      options,
      "ChainTimeout",
      fromCount
    );
  }

  subscribePotBoostedEvent(
    options: EventSubscribeOptions<ChainReactionTypes.PotBoostedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ChainReaction.contract,
      this,
      options,
      "PotBoosted",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | ChainReactionTypes.ChainStartedEvent
      | ChainReactionTypes.PlayerJoinedEvent
      | ChainReactionTypes.ChainEndedEvent
      | ChainReactionTypes.ChainTimeoutEvent
      | ChainReactionTypes.PotBoostedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      ChainReaction.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    startChain: async (
      params: ChainReactionTypes.CallMethodParams<"startChain">
    ): Promise<ChainReactionTypes.CallMethodResult<"startChain">> => {
      return callMethod(
        ChainReaction,
        this,
        "startChain",
        params,
        getContractByCodeHash
      );
    },
    joinChain: async (
      params: ChainReactionTypes.CallMethodParams<"joinChain">
    ): Promise<ChainReactionTypes.CallMethodResult<"joinChain">> => {
      return callMethod(
        ChainReaction,
        this,
        "joinChain",
        params,
        getContractByCodeHash
      );
    },
    endChain: async (
      params?: ChainReactionTypes.CallMethodParams<"endChain">
    ): Promise<ChainReactionTypes.CallMethodResult<"endChain">> => {
      return callMethod(
        ChainReaction,
        this,
        "endChain",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    canEnd: async (
      params?: ChainReactionTypes.CallMethodParams<"canEnd">
    ): Promise<ChainReactionTypes.CallMethodResult<"canEnd">> => {
      return callMethod(
        ChainReaction,
        this,
        "canEnd",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getChainInfo: async (
      params?: ChainReactionTypes.CallMethodParams<"getChainInfo">
    ): Promise<ChainReactionTypes.CallMethodResult<"getChainInfo">> => {
      return callMethod(
        ChainReaction,
        this,
        "getChainInfo",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    incentive: async (
      params: ChainReactionTypes.CallMethodParams<"incentive">
    ): Promise<ChainReactionTypes.CallMethodResult<"incentive">> => {
      return callMethod(
        ChainReaction,
        this,
        "incentive",
        params,
        getContractByCodeHash
      );
    },
    getNextEntryPrice: async (
      params?: ChainReactionTypes.CallMethodParams<"getNextEntryPrice">
    ): Promise<ChainReactionTypes.CallMethodResult<"getNextEntryPrice">> => {
      return callMethod(
        ChainReaction,
        this,
        "getNextEntryPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    startChain: async (
      params: ChainReactionTypes.SignExecuteMethodParams<"startChain">
    ): Promise<ChainReactionTypes.SignExecuteMethodResult<"startChain">> => {
      return signExecuteMethod(ChainReaction, this, "startChain", params);
    },
    joinChain: async (
      params: ChainReactionTypes.SignExecuteMethodParams<"joinChain">
    ): Promise<ChainReactionTypes.SignExecuteMethodResult<"joinChain">> => {
      return signExecuteMethod(ChainReaction, this, "joinChain", params);
    },
    endChain: async (
      params: ChainReactionTypes.SignExecuteMethodParams<"endChain">
    ): Promise<ChainReactionTypes.SignExecuteMethodResult<"endChain">> => {
      return signExecuteMethod(ChainReaction, this, "endChain", params);
    },
    canEnd: async (
      params: ChainReactionTypes.SignExecuteMethodParams<"canEnd">
    ): Promise<ChainReactionTypes.SignExecuteMethodResult<"canEnd">> => {
      return signExecuteMethod(ChainReaction, this, "canEnd", params);
    },
    getChainInfo: async (
      params: ChainReactionTypes.SignExecuteMethodParams<"getChainInfo">
    ): Promise<ChainReactionTypes.SignExecuteMethodResult<"getChainInfo">> => {
      return signExecuteMethod(ChainReaction, this, "getChainInfo", params);
    },
    incentive: async (
      params: ChainReactionTypes.SignExecuteMethodParams<"incentive">
    ): Promise<ChainReactionTypes.SignExecuteMethodResult<"incentive">> => {
      return signExecuteMethod(ChainReaction, this, "incentive", params);
    },
    getNextEntryPrice: async (
      params: ChainReactionTypes.SignExecuteMethodParams<"getNextEntryPrice">
    ): Promise<
      ChainReactionTypes.SignExecuteMethodResult<"getNextEntryPrice">
    > => {
      return signExecuteMethod(
        ChainReaction,
        this,
        "getNextEntryPrice",
        params
      );
    },
  };

  async multicall<Calls extends ChainReactionTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ChainReactionTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends ChainReactionTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<ChainReactionTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | ChainReactionTypes.MultiCallParams
      | ChainReactionTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      ChainReaction,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
