/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  RunScriptResult,
  DeployContractExecutionResult,
  NetworkId,
} from "@alephium/web3";
import {
  ChainReaction,
  ChainReactionInstance,
  FactoryChainReaction,
  FactoryChainReactionInstance,
  ChainReactionV3,
  ChainReactionV3Instance,
  FactoryChainReactionV2,
  FactoryChainReactionV2Instance,
  GameRoom,
  GameRoomInstance,
  GameHubFactory,
  GameHubFactoryInstance,
} from ".";
import { default as mainnetDeployments } from "../../deployments/.deployments.mainnet.json";
import { default as testnetDeployments } from "../../deployments/.deployments.testnet.json";
import { default as devnetDeployments } from "../../deployments/.deployments.devnet.json";

export type Deployments = {
  deployerAddress: string;
  contracts: {
    ChainReaction: DeployContractExecutionResult<ChainReactionInstance>;
    FactoryChainReaction: DeployContractExecutionResult<FactoryChainReactionInstance>;
    ChainReactionV3: DeployContractExecutionResult<ChainReactionV3Instance>;
    FactoryChainReactionV2: DeployContractExecutionResult<FactoryChainReactionV2Instance>;
    GameRoom?: DeployContractExecutionResult<GameRoomInstance>;
    GameHubFactory?: DeployContractExecutionResult<GameHubFactoryInstance>;
  };
};

function toDeployments(json: any): Deployments {
  const contracts = {
    ChainReaction: {
      ...json.contracts["ChainReaction"],
      contractInstance: ChainReaction.at(
        json.contracts["ChainReaction"].contractInstance.address
      ),
    },
    FactoryChainReaction: {
      ...json.contracts["FactoryChainReaction"],
      contractInstance: FactoryChainReaction.at(
        json.contracts["FactoryChainReaction"].contractInstance.address
      ),
    },
    ChainReactionV3: {
      ...json.contracts["ChainReactionV3"],
      contractInstance: ChainReactionV3.at(
        json.contracts["ChainReactionV3"].contractInstance.address
      ),
    },
    FactoryChainReactionV2: {
      ...json.contracts["FactoryChainReactionV2"],
      contractInstance: FactoryChainReactionV2.at(
        json.contracts["FactoryChainReactionV2"].contractInstance.address
      ),
    },
    GameRoom:
      json.contracts["GameRoom"] === undefined
        ? undefined
        : {
            ...json.contracts["GameRoom"],
            contractInstance: GameRoom.at(
              json.contracts["GameRoom"].contractInstance.address
            ),
          },
    GameHubFactory:
      json.contracts["GameHubFactory"] === undefined
        ? undefined
        : {
            ...json.contracts["GameHubFactory"],
            contractInstance: GameHubFactory.at(
              json.contracts["GameHubFactory"].contractInstance.address
            ),
          },
  };
  return {
    ...json,
    contracts: contracts as Deployments["contracts"],
  };
}

export function loadDeployments(
  networkId: NetworkId,
  deployerAddress?: string
): Deployments {
  const deployments =
    networkId === "mainnet"
      ? mainnetDeployments
      : networkId === "testnet"
      ? testnetDeployments
      : networkId === "devnet"
      ? devnetDeployments
      : undefined;
  if (deployments === undefined) {
    throw Error("The contract has not been deployed to the " + networkId);
  }
  const allDeployments: any[] = Array.isArray(deployments)
    ? deployments
    : [deployments];
  if (deployerAddress === undefined) {
    if (allDeployments.length > 1) {
      throw Error(
        "The contract has been deployed multiple times on " +
          networkId +
          ", please specify the deployer address"
      );
    } else {
      return toDeployments(allDeployments[0]);
    }
  }
  const result = allDeployments.find(
    (d) => d.deployerAddress === deployerAddress
  );
  if (result === undefined) {
    throw Error("The contract deployment result does not exist");
  }
  return toDeployments(result);
}
