/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FactoryChainReactionContractJson } from "../FactoryChainReaction.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace FactoryChainReactionTypes {
  export type Fields = {
    playContractTemplateId: HexString;
    numberGames: bigint;
  };

  export type State = ContractState<Fields>;

  export type NewGameCreatedEvent = ContractEvent<{
    contractId: HexString;
    gameId: bigint;
  }>;
  export type ChainStartedEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    startBlock: bigint;
  }>;
  export type PlayerJoinedEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    player: Address;
    entryFee: bigint;
    newPot: bigint;
    position: bigint;
    amountBurned: bigint;
  }>;
  export type ChainEndedEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    winner: Address;
    payout: bigint;
    totalBurned: bigint;
  }>;
  export type ChainTimeoutEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    player: Address;
  }>;
  export type PotBoostedEvent = ContractEvent<{
    gameContractId: HexString;
    caller: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    createNewGame: {
      params: CallContractParams<{
        durationDecreaseMsGame: bigint;
        minDurationGame: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    startChain: {
      params: CallContractParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        tokenIdGame: HexString;
        burnRate: bigint;
      }>;
      result: CallContractResult<null>;
    };
    joinChain: {
      params: CallContractParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
      }>;
      result: CallContractResult<null>;
    };
    endChain: {
      params: CallContractParams<{ gameContractId: HexString }>;
      result: CallContractResult<null>;
    };
    incentive: {
      params: CallContractParams<{
        gameContractId: HexString;
        amount: bigint;
        tokenId: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createNewGame: {
      params: SignExecuteContractMethodParams<{
        durationDecreaseMsGame: bigint;
        minDurationGame: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    startChain: {
      params: SignExecuteContractMethodParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        tokenIdGame: HexString;
        burnRate: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    joinChain: {
      params: SignExecuteContractMethodParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    endChain: {
      params: SignExecuteContractMethodParams<{ gameContractId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    incentive: {
      params: SignExecuteContractMethodParams<{
        gameContractId: HexString;
        amount: bigint;
        tokenId: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FactoryChainReactionInstance,
  FactoryChainReactionTypes.Fields
> {
  encodeFields(fields: FactoryChainReactionTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  eventIndex = {
    NewGameCreated: 0,
    ChainStarted: 1,
    PlayerJoined: 2,
    ChainEnded: 3,
    ChainTimeout: 4,
    PotBoosted: 5,
  };

  at(address: string): FactoryChainReactionInstance {
    return new FactoryChainReactionInstance(address);
  }

  tests = {
    createNewGame: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionTypes.Fields,
        { durationDecreaseMsGame: bigint; minDurationGame: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "createNewGame", params, getContractByCodeHash);
    },
    startChain: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionTypes.Fields,
        {
          gameContractId: HexString;
          payment: bigint;
          tokenId: HexString;
          durationGameMs: bigint;
          multiplierGameBps: bigint;
          tokenIdGame: HexString;
          burnRate: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "startChain", params, getContractByCodeHash);
    },
    joinChain: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionTypes.Fields,
        { gameContractId: HexString; payment: bigint; tokenId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "joinChain", params, getContractByCodeHash);
    },
    endChain: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionTypes.Fields,
        { gameContractId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "endChain", params, getContractByCodeHash);
    },
    incentive: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionTypes.Fields,
        { gameContractId: HexString; amount: bigint; tokenId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "incentive", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FactoryChainReactionTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FactoryChainReaction = new Factory(
  Contract.fromJson(
    FactoryChainReactionContractJson,
    "",
    "9f5030a2a662c0ba976d8025e9a5d6efe1959fb526ca07abcf7799ecd73ac646",
    types.AllStructs
  )
);
registerContract(FactoryChainReaction);

// Use this class to interact with the blockchain
export class FactoryChainReactionInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FactoryChainReactionTypes.State> {
    return fetchContractState(FactoryChainReaction, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeNewGameCreatedEvent(
    options: EventSubscribeOptions<FactoryChainReactionTypes.NewGameCreatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReaction.contract,
      this,
      options,
      "NewGameCreated",
      fromCount
    );
  }

  subscribeChainStartedEvent(
    options: EventSubscribeOptions<FactoryChainReactionTypes.ChainStartedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReaction.contract,
      this,
      options,
      "ChainStarted",
      fromCount
    );
  }

  subscribePlayerJoinedEvent(
    options: EventSubscribeOptions<FactoryChainReactionTypes.PlayerJoinedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReaction.contract,
      this,
      options,
      "PlayerJoined",
      fromCount
    );
  }

  subscribeChainEndedEvent(
    options: EventSubscribeOptions<FactoryChainReactionTypes.ChainEndedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReaction.contract,
      this,
      options,
      "ChainEnded",
      fromCount
    );
  }

  subscribeChainTimeoutEvent(
    options: EventSubscribeOptions<FactoryChainReactionTypes.ChainTimeoutEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReaction.contract,
      this,
      options,
      "ChainTimeout",
      fromCount
    );
  }

  subscribePotBoostedEvent(
    options: EventSubscribeOptions<FactoryChainReactionTypes.PotBoostedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReaction.contract,
      this,
      options,
      "PotBoosted",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | FactoryChainReactionTypes.NewGameCreatedEvent
      | FactoryChainReactionTypes.ChainStartedEvent
      | FactoryChainReactionTypes.PlayerJoinedEvent
      | FactoryChainReactionTypes.ChainEndedEvent
      | FactoryChainReactionTypes.ChainTimeoutEvent
      | FactoryChainReactionTypes.PotBoostedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      FactoryChainReaction.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    createNewGame: async (
      params: FactoryChainReactionTypes.CallMethodParams<"createNewGame">
    ): Promise<FactoryChainReactionTypes.CallMethodResult<"createNewGame">> => {
      return callMethod(
        FactoryChainReaction,
        this,
        "createNewGame",
        params,
        getContractByCodeHash
      );
    },
    startChain: async (
      params: FactoryChainReactionTypes.CallMethodParams<"startChain">
    ): Promise<FactoryChainReactionTypes.CallMethodResult<"startChain">> => {
      return callMethod(
        FactoryChainReaction,
        this,
        "startChain",
        params,
        getContractByCodeHash
      );
    },
    joinChain: async (
      params: FactoryChainReactionTypes.CallMethodParams<"joinChain">
    ): Promise<FactoryChainReactionTypes.CallMethodResult<"joinChain">> => {
      return callMethod(
        FactoryChainReaction,
        this,
        "joinChain",
        params,
        getContractByCodeHash
      );
    },
    endChain: async (
      params: FactoryChainReactionTypes.CallMethodParams<"endChain">
    ): Promise<FactoryChainReactionTypes.CallMethodResult<"endChain">> => {
      return callMethod(
        FactoryChainReaction,
        this,
        "endChain",
        params,
        getContractByCodeHash
      );
    },
    incentive: async (
      params: FactoryChainReactionTypes.CallMethodParams<"incentive">
    ): Promise<FactoryChainReactionTypes.CallMethodResult<"incentive">> => {
      return callMethod(
        FactoryChainReaction,
        this,
        "incentive",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createNewGame: async (
      params: FactoryChainReactionTypes.SignExecuteMethodParams<"createNewGame">
    ): Promise<
      FactoryChainReactionTypes.SignExecuteMethodResult<"createNewGame">
    > => {
      return signExecuteMethod(
        FactoryChainReaction,
        this,
        "createNewGame",
        params
      );
    },
    startChain: async (
      params: FactoryChainReactionTypes.SignExecuteMethodParams<"startChain">
    ): Promise<
      FactoryChainReactionTypes.SignExecuteMethodResult<"startChain">
    > => {
      return signExecuteMethod(
        FactoryChainReaction,
        this,
        "startChain",
        params
      );
    },
    joinChain: async (
      params: FactoryChainReactionTypes.SignExecuteMethodParams<"joinChain">
    ): Promise<
      FactoryChainReactionTypes.SignExecuteMethodResult<"joinChain">
    > => {
      return signExecuteMethod(FactoryChainReaction, this, "joinChain", params);
    },
    endChain: async (
      params: FactoryChainReactionTypes.SignExecuteMethodParams<"endChain">
    ): Promise<
      FactoryChainReactionTypes.SignExecuteMethodResult<"endChain">
    > => {
      return signExecuteMethod(FactoryChainReaction, this, "endChain", params);
    },
    incentive: async (
      params: FactoryChainReactionTypes.SignExecuteMethodParams<"incentive">
    ): Promise<
      FactoryChainReactionTypes.SignExecuteMethodResult<"incentive">
    > => {
      return signExecuteMethod(FactoryChainReaction, this, "incentive", params);
    },
  };

  async multicall<Calls extends FactoryChainReactionTypes.MultiCallParams>(
    calls: Calls
  ): Promise<FactoryChainReactionTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends FactoryChainReactionTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FactoryChainReactionTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FactoryChainReactionTypes.MultiCallParams
      | FactoryChainReactionTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FactoryChainReaction,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
