/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as FactoryChainReactionV2ContractJson } from "../FactoryChainReactionV2.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace FactoryChainReactionV2Types {
  export type Fields = {
    playContractTemplateId: HexString;
    numberGames: bigint;
  };

  export type State = ContractState<Fields>;

  export type NewGameCreatedEvent = ContractEvent<{
    contractId: HexString;
    gameId: bigint;
    isFixedTokenId: boolean;
    tokenId: HexString;
  }>;
  export type ChainStartedEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    startBlock: bigint;
    feesBps: bigint;
    tokenId: HexString;
  }>;
  export type PlayerJoinedEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    player: Address;
    entryFee: bigint;
    newPot: bigint;
    position: bigint;
    amountBurned: bigint;
    tokenId: HexString;
  }>;
  export type ChainEndedEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    winner: Address;
    payout: bigint;
    totalBurned: bigint;
    feesAmount: bigint;
  }>;
  export type ChainTimeoutEvent = ContractEvent<{
    gameContractId: HexString;
    chainId: bigint;
    player: Address;
  }>;
  export type PotBoostedEvent = ContractEvent<{
    gameContractId: HexString;
    caller: Address;
    amount: bigint;
  }>;

  export interface CallMethodTable {
    createNewGame: {
      params: CallContractParams<{
        durationDecreaseMsGame: bigint;
        minDurationGame: bigint;
        addrFees: Address;
        isFixedTokenId: boolean;
        tokenId: HexString;
      }>;
      result: CallContractResult<HexString>;
    };
    startChain: {
      params: CallContractParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        burnRate: bigint;
        feesBps: bigint;
        decayPeriodMs: bigint;
      }>;
      result: CallContractResult<null>;
    };
    joinChain: {
      params: CallContractParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
      }>;
      result: CallContractResult<null>;
    };
    endChain: {
      params: CallContractParams<{ gameContractId: HexString }>;
      result: CallContractResult<null>;
    };
    incentive: {
      params: CallContractParams<{
        gameContractId: HexString;
        amount: bigint;
        tokenId: HexString;
      }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createNewGame: {
      params: SignExecuteContractMethodParams<{
        durationDecreaseMsGame: bigint;
        minDurationGame: bigint;
        addrFees: Address;
        isFixedTokenId: boolean;
        tokenId: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    startChain: {
      params: SignExecuteContractMethodParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
        durationGameMs: bigint;
        multiplierGameBps: bigint;
        burnRate: bigint;
        feesBps: bigint;
        decayPeriodMs: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    joinChain: {
      params: SignExecuteContractMethodParams<{
        gameContractId: HexString;
        payment: bigint;
        tokenId: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    endChain: {
      params: SignExecuteContractMethodParams<{ gameContractId: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    incentive: {
      params: SignExecuteContractMethodParams<{
        gameContractId: HexString;
        amount: bigint;
        tokenId: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  FactoryChainReactionV2Instance,
  FactoryChainReactionV2Types.Fields
> {
  encodeFields(fields: FactoryChainReactionV2Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  eventIndex = {
    NewGameCreated: 0,
    ChainStarted: 1,
    PlayerJoined: 2,
    ChainEnded: 3,
    ChainTimeout: 4,
    PotBoosted: 5,
  };

  at(address: string): FactoryChainReactionV2Instance {
    return new FactoryChainReactionV2Instance(address);
  }

  tests = {
    createNewGame: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionV2Types.Fields,
        {
          durationDecreaseMsGame: bigint;
          minDurationGame: bigint;
          addrFees: Address;
          isFixedTokenId: boolean;
          tokenId: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "createNewGame", params, getContractByCodeHash);
    },
    startChain: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionV2Types.Fields,
        {
          gameContractId: HexString;
          payment: bigint;
          tokenId: HexString;
          durationGameMs: bigint;
          multiplierGameBps: bigint;
          burnRate: bigint;
          feesBps: bigint;
          decayPeriodMs: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "startChain", params, getContractByCodeHash);
    },
    joinChain: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionV2Types.Fields,
        { gameContractId: HexString; payment: bigint; tokenId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "joinChain", params, getContractByCodeHash);
    },
    endChain: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionV2Types.Fields,
        { gameContractId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "endChain", params, getContractByCodeHash);
    },
    incentive: async (
      params: TestContractParamsWithoutMaps<
        FactoryChainReactionV2Types.Fields,
        { gameContractId: HexString; amount: bigint; tokenId: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "incentive", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: FactoryChainReactionV2Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const FactoryChainReactionV2 = new Factory(
  Contract.fromJson(
    FactoryChainReactionV2ContractJson,
    "",
    "74aedc46a5e29dfb413873ea10a2f8c89ae78bd1c8757a587631331fe6e5faa2",
    types.AllStructs
  )
);
registerContract(FactoryChainReactionV2);

// Use this class to interact with the blockchain
export class FactoryChainReactionV2Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<FactoryChainReactionV2Types.State> {
    return fetchContractState(FactoryChainReactionV2, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeNewGameCreatedEvent(
    options: EventSubscribeOptions<FactoryChainReactionV2Types.NewGameCreatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReactionV2.contract,
      this,
      options,
      "NewGameCreated",
      fromCount
    );
  }

  subscribeChainStartedEvent(
    options: EventSubscribeOptions<FactoryChainReactionV2Types.ChainStartedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReactionV2.contract,
      this,
      options,
      "ChainStarted",
      fromCount
    );
  }

  subscribePlayerJoinedEvent(
    options: EventSubscribeOptions<FactoryChainReactionV2Types.PlayerJoinedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReactionV2.contract,
      this,
      options,
      "PlayerJoined",
      fromCount
    );
  }

  subscribeChainEndedEvent(
    options: EventSubscribeOptions<FactoryChainReactionV2Types.ChainEndedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReactionV2.contract,
      this,
      options,
      "ChainEnded",
      fromCount
    );
  }

  subscribeChainTimeoutEvent(
    options: EventSubscribeOptions<FactoryChainReactionV2Types.ChainTimeoutEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReactionV2.contract,
      this,
      options,
      "ChainTimeout",
      fromCount
    );
  }

  subscribePotBoostedEvent(
    options: EventSubscribeOptions<FactoryChainReactionV2Types.PotBoostedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      FactoryChainReactionV2.contract,
      this,
      options,
      "PotBoosted",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | FactoryChainReactionV2Types.NewGameCreatedEvent
      | FactoryChainReactionV2Types.ChainStartedEvent
      | FactoryChainReactionV2Types.PlayerJoinedEvent
      | FactoryChainReactionV2Types.ChainEndedEvent
      | FactoryChainReactionV2Types.ChainTimeoutEvent
      | FactoryChainReactionV2Types.PotBoostedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      FactoryChainReactionV2.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    createNewGame: async (
      params: FactoryChainReactionV2Types.CallMethodParams<"createNewGame">
    ): Promise<
      FactoryChainReactionV2Types.CallMethodResult<"createNewGame">
    > => {
      return callMethod(
        FactoryChainReactionV2,
        this,
        "createNewGame",
        params,
        getContractByCodeHash
      );
    },
    startChain: async (
      params: FactoryChainReactionV2Types.CallMethodParams<"startChain">
    ): Promise<FactoryChainReactionV2Types.CallMethodResult<"startChain">> => {
      return callMethod(
        FactoryChainReactionV2,
        this,
        "startChain",
        params,
        getContractByCodeHash
      );
    },
    joinChain: async (
      params: FactoryChainReactionV2Types.CallMethodParams<"joinChain">
    ): Promise<FactoryChainReactionV2Types.CallMethodResult<"joinChain">> => {
      return callMethod(
        FactoryChainReactionV2,
        this,
        "joinChain",
        params,
        getContractByCodeHash
      );
    },
    endChain: async (
      params: FactoryChainReactionV2Types.CallMethodParams<"endChain">
    ): Promise<FactoryChainReactionV2Types.CallMethodResult<"endChain">> => {
      return callMethod(
        FactoryChainReactionV2,
        this,
        "endChain",
        params,
        getContractByCodeHash
      );
    },
    incentive: async (
      params: FactoryChainReactionV2Types.CallMethodParams<"incentive">
    ): Promise<FactoryChainReactionV2Types.CallMethodResult<"incentive">> => {
      return callMethod(
        FactoryChainReactionV2,
        this,
        "incentive",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createNewGame: async (
      params: FactoryChainReactionV2Types.SignExecuteMethodParams<"createNewGame">
    ): Promise<
      FactoryChainReactionV2Types.SignExecuteMethodResult<"createNewGame">
    > => {
      return signExecuteMethod(
        FactoryChainReactionV2,
        this,
        "createNewGame",
        params
      );
    },
    startChain: async (
      params: FactoryChainReactionV2Types.SignExecuteMethodParams<"startChain">
    ): Promise<
      FactoryChainReactionV2Types.SignExecuteMethodResult<"startChain">
    > => {
      return signExecuteMethod(
        FactoryChainReactionV2,
        this,
        "startChain",
        params
      );
    },
    joinChain: async (
      params: FactoryChainReactionV2Types.SignExecuteMethodParams<"joinChain">
    ): Promise<
      FactoryChainReactionV2Types.SignExecuteMethodResult<"joinChain">
    > => {
      return signExecuteMethod(
        FactoryChainReactionV2,
        this,
        "joinChain",
        params
      );
    },
    endChain: async (
      params: FactoryChainReactionV2Types.SignExecuteMethodParams<"endChain">
    ): Promise<
      FactoryChainReactionV2Types.SignExecuteMethodResult<"endChain">
    > => {
      return signExecuteMethod(
        FactoryChainReactionV2,
        this,
        "endChain",
        params
      );
    },
    incentive: async (
      params: FactoryChainReactionV2Types.SignExecuteMethodParams<"incentive">
    ): Promise<
      FactoryChainReactionV2Types.SignExecuteMethodResult<"incentive">
    > => {
      return signExecuteMethod(
        FactoryChainReactionV2,
        this,
        "incentive",
        params
      );
    },
  };

  async multicall<Calls extends FactoryChainReactionV2Types.MultiCallParams>(
    calls: Calls
  ): Promise<FactoryChainReactionV2Types.MultiCallResults<Calls>>;
  async multicall<Callss extends FactoryChainReactionV2Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<FactoryChainReactionV2Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | FactoryChainReactionV2Types.MultiCallParams
      | FactoryChainReactionV2Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      FactoryChainReactionV2,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
