/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as GameHubFactoryContractJson } from "../GameHubFactory.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace GameHubFactoryTypes {
  export type Fields = {
    gameRoomTemplateId: HexString;
    oracleContractId: HexString;
    totalRooms: bigint;
  };

  export type State = ContractState<Fields>;

  export type RoomCreatedEvent = ContractEvent<{
    roomContractId: HexString;
    creator: Address;
    entryFee: bigint;
    maxPlayers: bigint;
    numberRangeMax: bigint;
    expiresAt: bigint;
  }>;

  export interface CallMethodTable {
    createRoom: {
      params: CallContractParams<{
        entryFee: bigint;
        maxPlayers: bigint;
        numberRangeMax: bigint;
        expiresAt: bigint;
      }>;
      result: CallContractResult<HexString>;
    };
    getTotalRooms: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getOracleContractId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    createRoom: {
      params: SignExecuteContractMethodParams<{
        entryFee: bigint;
        maxPlayers: bigint;
        numberRangeMax: bigint;
        expiresAt: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getTotalRooms: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getOracleContractId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  GameHubFactoryInstance,
  GameHubFactoryTypes.Fields
> {
  encodeFields(fields: GameHubFactoryTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  eventIndex = { RoomCreated: 0 };
  consts = {
    ErrorCodes: {
      InvalidMaxPlayers: BigInt("0"),
      InvalidNumberRange: BigInt("1"),
      InvalidExpiresAt: BigInt("2"),
      InvalidEntryFee: BigInt("3"),
    },
  };

  at(address: string): GameHubFactoryInstance {
    return new GameHubFactoryInstance(address);
  }

  tests = {
    createRoom: async (
      params: TestContractParamsWithoutMaps<
        GameHubFactoryTypes.Fields,
        {
          entryFee: bigint;
          maxPlayers: bigint;
          numberRangeMax: bigint;
          expiresAt: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "createRoom", params, getContractByCodeHash);
    },
    getTotalRooms: async (
      params: Omit<
        TestContractParamsWithoutMaps<GameHubFactoryTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalRooms", params, getContractByCodeHash);
    },
    getOracleContractId: async (
      params: Omit<
        TestContractParamsWithoutMaps<GameHubFactoryTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getOracleContractId",
        params,
        getContractByCodeHash
      );
    },
  };

  stateForTest(
    initFields: GameHubFactoryTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const GameHubFactory = new Factory(
  Contract.fromJson(
    GameHubFactoryContractJson,
    "",
    "d0d3cf79f3d841014bbb3700d93a98f163edb14fc15a047fff772aadb69d412b",
    types.AllStructs
  )
);
registerContract(GameHubFactory);

// Use this class to interact with the blockchain
export class GameHubFactoryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<GameHubFactoryTypes.State> {
    return fetchContractState(GameHubFactory, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeRoomCreatedEvent(
    options: EventSubscribeOptions<GameHubFactoryTypes.RoomCreatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameHubFactory.contract,
      this,
      options,
      "RoomCreated",
      fromCount
    );
  }

  view = {
    createRoom: async (
      params: GameHubFactoryTypes.CallMethodParams<"createRoom">
    ): Promise<GameHubFactoryTypes.CallMethodResult<"createRoom">> => {
      return callMethod(
        GameHubFactory,
        this,
        "createRoom",
        params,
        getContractByCodeHash
      );
    },
    getTotalRooms: async (
      params?: GameHubFactoryTypes.CallMethodParams<"getTotalRooms">
    ): Promise<GameHubFactoryTypes.CallMethodResult<"getTotalRooms">> => {
      return callMethod(
        GameHubFactory,
        this,
        "getTotalRooms",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getOracleContractId: async (
      params?: GameHubFactoryTypes.CallMethodParams<"getOracleContractId">
    ): Promise<GameHubFactoryTypes.CallMethodResult<"getOracleContractId">> => {
      return callMethod(
        GameHubFactory,
        this,
        "getOracleContractId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    createRoom: async (
      params: GameHubFactoryTypes.SignExecuteMethodParams<"createRoom">
    ): Promise<GameHubFactoryTypes.SignExecuteMethodResult<"createRoom">> => {
      return signExecuteMethod(GameHubFactory, this, "createRoom", params);
    },
    getTotalRooms: async (
      params: GameHubFactoryTypes.SignExecuteMethodParams<"getTotalRooms">
    ): Promise<
      GameHubFactoryTypes.SignExecuteMethodResult<"getTotalRooms">
    > => {
      return signExecuteMethod(GameHubFactory, this, "getTotalRooms", params);
    },
    getOracleContractId: async (
      params: GameHubFactoryTypes.SignExecuteMethodParams<"getOracleContractId">
    ): Promise<
      GameHubFactoryTypes.SignExecuteMethodResult<"getOracleContractId">
    > => {
      return signExecuteMethod(
        GameHubFactory,
        this,
        "getOracleContractId",
        params
      );
    },
  };

  async multicall<Calls extends GameHubFactoryTypes.MultiCallParams>(
    calls: Calls
  ): Promise<GameHubFactoryTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends GameHubFactoryTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<GameHubFactoryTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | GameHubFactoryTypes.MultiCallParams
      | GameHubFactoryTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      GameHubFactory,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
