/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as GameRoomContractJson } from "../GameRoom.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace GameRoomTypes {
  export type Fields = {
    entryFee: bigint;
    maxPlayers: bigint;
    numberRangeMax: bigint;
    expiresAt: bigint;
    creator: Address;
    oracle: HexString;
    state: bigint;
    playerCount: bigint;
    pot: bigint;
    target: bigint;
    lockedAt: bigint;
    lockedAtRound: bigint;
    finalizedAt: bigint;
    creatorFeeEnabled: boolean;
    snapshotPot: bigint;
  };

  export type State = ContractState<Fields>;

  export type PlayerJoinedEvent = ContractEvent<{
    roomId: HexString;
    player: Address;
    number: bigint;
  }>;
  export type RoomLockedEvent = ContractEvent<{
    roomId: HexString;
    lockedAtRound: bigint;
  }>;
  export type RoomClaimableEvent = ContractEvent<{
    roomId: HexString;
    target: bigint;
  }>;
  export type ClaimedEvent = ContractEvent<{
    roomId: HexString;
    player: Address;
    payout: bigint;
  }>;
  export type ForceClaimedEvent = ContractEvent<{
    roomId: HexString;
    player: Address;
    payout: bigint;
    caller: Address;
  }>;
  export type RefundedEvent = ContractEvent<{
    roomId: HexString;
    player: Address;
  }>;
  export type RoomDestroyedEvent = ContractEvent<{
    roomId: HexString;
    creatorCut: bigint;
  }>;
  export type RoomExpiredEvent = ContractEvent<{ roomId: HexString }>;
  export type PotBoostedEvent = ContractEvent<{
    roomId: HexString;
    booster: Address;
    amount: bigint;
    newPot: bigint;
  }>;

  export interface CallMethodTable {
    joinRoom: {
      params: CallContractParams<{ number: bigint }>;
      result: CallContractResult<null>;
    };
    resolveRandomness: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    claim: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    forceClaim: {
      params: CallContractParams<{ player: Address }>;
      result: CallContractResult<null>;
    };
    refund: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    expireRoom: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    boostPot: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    destroy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    getState: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getPlayerCount: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTarget: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getPot: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getPlayerPayout: {
      params: CallContractParams<{ player: Address }>;
      result: CallContractResult<bigint>;
    };
    getRoomInfo: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<[bigint, bigint, bigint, bigint, Address]>;
    };
    bandPayout: {
      params: CallContractParams<{ num: bigint }>;
      result: CallContractResult<bigint>;
    };
    absDiff: {
      params: CallContractParams<{ a: bigint; b: bigint }>;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    joinRoom: {
      params: SignExecuteContractMethodParams<{ number: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    resolveRandomness: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    claim: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    forceClaim: {
      params: SignExecuteContractMethodParams<{ player: Address }>;
      result: SignExecuteScriptTxResult;
    };
    refund: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    expireRoom: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    boostPot: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    destroy: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getState: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getPlayerCount: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTarget: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getPot: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getPlayerPayout: {
      params: SignExecuteContractMethodParams<{ player: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getRoomInfo: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    bandPayout: {
      params: SignExecuteContractMethodParams<{ num: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    absDiff: {
      params: SignExecuteContractMethodParams<{ a: bigint; b: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { playerNumber?: Map<Address, bigint> };
}

class Factory extends ContractFactory<GameRoomInstance, GameRoomTypes.Fields> {
  encodeFields(fields: GameRoomTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  eventIndex = {
    PlayerJoined: 0,
    RoomLocked: 1,
    RoomClaimable: 2,
    Claimed: 3,
    ForceClaimed: 4,
    Refunded: 5,
    RoomDestroyed: 6,
    RoomExpired: 7,
    PotBoosted: 8,
  };
  consts = {
    OPEN: BigInt("0"),
    LOCKED: BigInt("1"),
    CLAIMABLE: BigInt("2"),
    EXPIRED: BigInt("3"),
    DESTROYED: BigInt("4"),
    CREATOR_FEE_BPS: BigInt("500"),
    ROUNDS_DELAY: BigInt("3"),
    RANDOMNESS_DELAY_MS: BigInt("90000"),
    LOCKED_TIMEOUT_MS: BigInt("86400000"),
    FORCE_CLAIM_GRACE_MS: BigInt("259200000"),
    ErrorCodes: {
      RoomNotOpen: BigInt("0"),
      RoomNotLocked: BigInt("1"),
      RoomNotClaimable: BigInt("2"),
      RoomFull: BigInt("4"),
      NumberOutOfRange: BigInt("5"),
      NotExpired: BigInt("7"),
      NotPlayer: BigInt("9"),
      AlreadyClaimed: BigInt("11"),
      TooEarlyToResolve: BigInt("14"),
      AlreadyExpired: BigInt("15"),
      PlayersRemaining: BigInt("16"),
      AlreadyJoined: BigInt("17"),
      CannotForceSelf: BigInt("18"),
      RoomNotDestroyable: BigInt("19"),
      TooEarlyToForceClaim: BigInt("20"),
      RoomEnded: BigInt("21"),
    },
  };

  at(address: string): GameRoomInstance {
    return new GameRoomInstance(address);
  }

  tests = {
    joinRoom: async (
      params: TestContractParams<
        GameRoomTypes.Fields,
        { number: bigint },
        GameRoomTypes.Maps
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(this, "joinRoom", params, getContractByCodeHash);
    },
    resolveRandomness: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(
        this,
        "resolveRandomness",
        params,
        getContractByCodeHash
      );
    },
    claim: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(this, "claim", params, getContractByCodeHash);
    },
    forceClaim: async (
      params: TestContractParams<
        GameRoomTypes.Fields,
        { player: Address },
        GameRoomTypes.Maps
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(this, "forceClaim", params, getContractByCodeHash);
    },
    refund: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(this, "refund", params, getContractByCodeHash);
    },
    expireRoom: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(this, "expireRoom", params, getContractByCodeHash);
    },
    boostPot: async (
      params: TestContractParams<
        GameRoomTypes.Fields,
        { amount: bigint },
        GameRoomTypes.Maps
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(this, "boostPot", params, getContractByCodeHash);
    },
    destroy: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<null, GameRoomTypes.Maps>> => {
      return testMethod(this, "destroy", params, getContractByCodeHash);
    },
    getState: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<bigint, GameRoomTypes.Maps>> => {
      return testMethod(this, "getState", params, getContractByCodeHash);
    },
    getPlayerCount: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<bigint, GameRoomTypes.Maps>> => {
      return testMethod(this, "getPlayerCount", params, getContractByCodeHash);
    },
    getTarget: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<bigint, GameRoomTypes.Maps>> => {
      return testMethod(this, "getTarget", params, getContractByCodeHash);
    },
    getPot: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<TestContractResult<bigint, GameRoomTypes.Maps>> => {
      return testMethod(this, "getPot", params, getContractByCodeHash);
    },
    getPlayerPayout: async (
      params: TestContractParams<
        GameRoomTypes.Fields,
        { player: Address },
        GameRoomTypes.Maps
      >
    ): Promise<TestContractResult<bigint, GameRoomTypes.Maps>> => {
      return testMethod(this, "getPlayerPayout", params, getContractByCodeHash);
    },
    getRoomInfo: async (
      params: Omit<
        TestContractParams<GameRoomTypes.Fields, never, GameRoomTypes.Maps>,
        "args"
      >
    ): Promise<
      TestContractResult<
        [bigint, bigint, bigint, bigint, Address],
        GameRoomTypes.Maps
      >
    > => {
      return testMethod(this, "getRoomInfo", params, getContractByCodeHash);
    },
    bandPayout: async (
      params: TestContractParams<
        GameRoomTypes.Fields,
        { num: bigint },
        GameRoomTypes.Maps
      >
    ): Promise<TestContractResult<bigint, GameRoomTypes.Maps>> => {
      return testMethod(this, "bandPayout", params, getContractByCodeHash);
    },
    absDiff: async (
      params: TestContractParams<
        GameRoomTypes.Fields,
        { a: bigint; b: bigint },
        GameRoomTypes.Maps
      >
    ): Promise<TestContractResult<bigint, GameRoomTypes.Maps>> => {
      return testMethod(this, "absDiff", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: GameRoomTypes.Fields,
    asset?: Asset,
    address?: string,
    maps?: GameRoomTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const GameRoom = new Factory(
  Contract.fromJson(
    GameRoomContractJson,
    "=6-2+bb=1+1=1-2+6=2-1=1-4+c=2-2+7b=2-1+e=2+3=2-1=2-1+6=3-2+c0=2-2+ce=2-2+dc=2-2+ea=2-2+f84=3-1=2+55=1-1+4a6=2-1=1+f=13-1+9=194+7a7e0214696e73657274206174206d617020706174683a2000=279-1+4=200+7a7e021472656d6f7665206174206d617020706174683a2000=81-1+d=278+7a7e021472656d6f7665206174206d617020706174683a2000=85-1+a=110+7a7e021472656d6f7665206174206d617020706174683a2000=986",
    "cc969547eb14bb23c6528fa34b2adea759ab36b9e5a4b7e7e3cc127768c165a0",
    types.AllStructs
  )
);
registerContract(GameRoom);

// Use this class to interact with the blockchain
export class GameRoomInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    playerNumber: new RalphMap<Address, bigint>(
      GameRoom.contract,
      this.contractId,
      "playerNumber"
    ),
  };

  async fetchState(): Promise<GameRoomTypes.State> {
    return fetchContractState(GameRoom, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribePlayerJoinedEvent(
    options: EventSubscribeOptions<GameRoomTypes.PlayerJoinedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "PlayerJoined",
      fromCount
    );
  }

  subscribeRoomLockedEvent(
    options: EventSubscribeOptions<GameRoomTypes.RoomLockedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "RoomLocked",
      fromCount
    );
  }

  subscribeRoomClaimableEvent(
    options: EventSubscribeOptions<GameRoomTypes.RoomClaimableEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "RoomClaimable",
      fromCount
    );
  }

  subscribeClaimedEvent(
    options: EventSubscribeOptions<GameRoomTypes.ClaimedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "Claimed",
      fromCount
    );
  }

  subscribeForceClaimedEvent(
    options: EventSubscribeOptions<GameRoomTypes.ForceClaimedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "ForceClaimed",
      fromCount
    );
  }

  subscribeRefundedEvent(
    options: EventSubscribeOptions<GameRoomTypes.RefundedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "Refunded",
      fromCount
    );
  }

  subscribeRoomDestroyedEvent(
    options: EventSubscribeOptions<GameRoomTypes.RoomDestroyedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "RoomDestroyed",
      fromCount
    );
  }

  subscribeRoomExpiredEvent(
    options: EventSubscribeOptions<GameRoomTypes.RoomExpiredEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "RoomExpired",
      fromCount
    );
  }

  subscribePotBoostedEvent(
    options: EventSubscribeOptions<GameRoomTypes.PotBoostedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      GameRoom.contract,
      this,
      options,
      "PotBoosted",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | GameRoomTypes.PlayerJoinedEvent
      | GameRoomTypes.RoomLockedEvent
      | GameRoomTypes.RoomClaimableEvent
      | GameRoomTypes.ClaimedEvent
      | GameRoomTypes.ForceClaimedEvent
      | GameRoomTypes.RefundedEvent
      | GameRoomTypes.RoomDestroyedEvent
      | GameRoomTypes.RoomExpiredEvent
      | GameRoomTypes.PotBoostedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(GameRoom.contract, this, options, fromCount);
  }

  view = {
    joinRoom: async (
      params: GameRoomTypes.CallMethodParams<"joinRoom">
    ): Promise<GameRoomTypes.CallMethodResult<"joinRoom">> => {
      return callMethod(
        GameRoom,
        this,
        "joinRoom",
        params,
        getContractByCodeHash
      );
    },
    resolveRandomness: async (
      params?: GameRoomTypes.CallMethodParams<"resolveRandomness">
    ): Promise<GameRoomTypes.CallMethodResult<"resolveRandomness">> => {
      return callMethod(
        GameRoom,
        this,
        "resolveRandomness",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    claim: async (
      params?: GameRoomTypes.CallMethodParams<"claim">
    ): Promise<GameRoomTypes.CallMethodResult<"claim">> => {
      return callMethod(
        GameRoom,
        this,
        "claim",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    forceClaim: async (
      params: GameRoomTypes.CallMethodParams<"forceClaim">
    ): Promise<GameRoomTypes.CallMethodResult<"forceClaim">> => {
      return callMethod(
        GameRoom,
        this,
        "forceClaim",
        params,
        getContractByCodeHash
      );
    },
    refund: async (
      params?: GameRoomTypes.CallMethodParams<"refund">
    ): Promise<GameRoomTypes.CallMethodResult<"refund">> => {
      return callMethod(
        GameRoom,
        this,
        "refund",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    expireRoom: async (
      params?: GameRoomTypes.CallMethodParams<"expireRoom">
    ): Promise<GameRoomTypes.CallMethodResult<"expireRoom">> => {
      return callMethod(
        GameRoom,
        this,
        "expireRoom",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    boostPot: async (
      params: GameRoomTypes.CallMethodParams<"boostPot">
    ): Promise<GameRoomTypes.CallMethodResult<"boostPot">> => {
      return callMethod(
        GameRoom,
        this,
        "boostPot",
        params,
        getContractByCodeHash
      );
    },
    destroy: async (
      params?: GameRoomTypes.CallMethodParams<"destroy">
    ): Promise<GameRoomTypes.CallMethodResult<"destroy">> => {
      return callMethod(
        GameRoom,
        this,
        "destroy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getState: async (
      params?: GameRoomTypes.CallMethodParams<"getState">
    ): Promise<GameRoomTypes.CallMethodResult<"getState">> => {
      return callMethod(
        GameRoom,
        this,
        "getState",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getPlayerCount: async (
      params?: GameRoomTypes.CallMethodParams<"getPlayerCount">
    ): Promise<GameRoomTypes.CallMethodResult<"getPlayerCount">> => {
      return callMethod(
        GameRoom,
        this,
        "getPlayerCount",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTarget: async (
      params?: GameRoomTypes.CallMethodParams<"getTarget">
    ): Promise<GameRoomTypes.CallMethodResult<"getTarget">> => {
      return callMethod(
        GameRoom,
        this,
        "getTarget",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getPot: async (
      params?: GameRoomTypes.CallMethodParams<"getPot">
    ): Promise<GameRoomTypes.CallMethodResult<"getPot">> => {
      return callMethod(
        GameRoom,
        this,
        "getPot",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getPlayerPayout: async (
      params: GameRoomTypes.CallMethodParams<"getPlayerPayout">
    ): Promise<GameRoomTypes.CallMethodResult<"getPlayerPayout">> => {
      return callMethod(
        GameRoom,
        this,
        "getPlayerPayout",
        params,
        getContractByCodeHash
      );
    },
    getRoomInfo: async (
      params?: GameRoomTypes.CallMethodParams<"getRoomInfo">
    ): Promise<GameRoomTypes.CallMethodResult<"getRoomInfo">> => {
      return callMethod(
        GameRoom,
        this,
        "getRoomInfo",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    bandPayout: async (
      params: GameRoomTypes.CallMethodParams<"bandPayout">
    ): Promise<GameRoomTypes.CallMethodResult<"bandPayout">> => {
      return callMethod(
        GameRoom,
        this,
        "bandPayout",
        params,
        getContractByCodeHash
      );
    },
    absDiff: async (
      params: GameRoomTypes.CallMethodParams<"absDiff">
    ): Promise<GameRoomTypes.CallMethodResult<"absDiff">> => {
      return callMethod(
        GameRoom,
        this,
        "absDiff",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    joinRoom: async (
      params: GameRoomTypes.SignExecuteMethodParams<"joinRoom">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"joinRoom">> => {
      return signExecuteMethod(GameRoom, this, "joinRoom", params);
    },
    resolveRandomness: async (
      params: GameRoomTypes.SignExecuteMethodParams<"resolveRandomness">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"resolveRandomness">> => {
      return signExecuteMethod(GameRoom, this, "resolveRandomness", params);
    },
    claim: async (
      params: GameRoomTypes.SignExecuteMethodParams<"claim">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"claim">> => {
      return signExecuteMethod(GameRoom, this, "claim", params);
    },
    forceClaim: async (
      params: GameRoomTypes.SignExecuteMethodParams<"forceClaim">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"forceClaim">> => {
      return signExecuteMethod(GameRoom, this, "forceClaim", params);
    },
    refund: async (
      params: GameRoomTypes.SignExecuteMethodParams<"refund">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"refund">> => {
      return signExecuteMethod(GameRoom, this, "refund", params);
    },
    expireRoom: async (
      params: GameRoomTypes.SignExecuteMethodParams<"expireRoom">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"expireRoom">> => {
      return signExecuteMethod(GameRoom, this, "expireRoom", params);
    },
    boostPot: async (
      params: GameRoomTypes.SignExecuteMethodParams<"boostPot">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"boostPot">> => {
      return signExecuteMethod(GameRoom, this, "boostPot", params);
    },
    destroy: async (
      params: GameRoomTypes.SignExecuteMethodParams<"destroy">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"destroy">> => {
      return signExecuteMethod(GameRoom, this, "destroy", params);
    },
    getState: async (
      params: GameRoomTypes.SignExecuteMethodParams<"getState">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"getState">> => {
      return signExecuteMethod(GameRoom, this, "getState", params);
    },
    getPlayerCount: async (
      params: GameRoomTypes.SignExecuteMethodParams<"getPlayerCount">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"getPlayerCount">> => {
      return signExecuteMethod(GameRoom, this, "getPlayerCount", params);
    },
    getTarget: async (
      params: GameRoomTypes.SignExecuteMethodParams<"getTarget">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"getTarget">> => {
      return signExecuteMethod(GameRoom, this, "getTarget", params);
    },
    getPot: async (
      params: GameRoomTypes.SignExecuteMethodParams<"getPot">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"getPot">> => {
      return signExecuteMethod(GameRoom, this, "getPot", params);
    },
    getPlayerPayout: async (
      params: GameRoomTypes.SignExecuteMethodParams<"getPlayerPayout">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"getPlayerPayout">> => {
      return signExecuteMethod(GameRoom, this, "getPlayerPayout", params);
    },
    getRoomInfo: async (
      params: GameRoomTypes.SignExecuteMethodParams<"getRoomInfo">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"getRoomInfo">> => {
      return signExecuteMethod(GameRoom, this, "getRoomInfo", params);
    },
    bandPayout: async (
      params: GameRoomTypes.SignExecuteMethodParams<"bandPayout">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"bandPayout">> => {
      return signExecuteMethod(GameRoom, this, "bandPayout", params);
    },
    absDiff: async (
      params: GameRoomTypes.SignExecuteMethodParams<"absDiff">
    ): Promise<GameRoomTypes.SignExecuteMethodResult<"absDiff">> => {
      return signExecuteMethod(GameRoom, this, "absDiff", params);
    },
  };

  async multicall<Calls extends GameRoomTypes.MultiCallParams>(
    calls: Calls
  ): Promise<GameRoomTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends GameRoomTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<GameRoomTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | GameRoomTypes.MultiCallParams
      | GameRoomTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      GameRoom,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
