/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as MockDIAOracleContractJson } from "../MockDIAOracle.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";
import * as types from "./types";

// Custom types for the contract
export namespace MockDIAOracleTypes {
  export type Fields = {
    lastRound: bigint;
    randomBytes: HexString;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getLastRound: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getRandomValue: {
      params: CallContractParams<{ round: bigint }>;
      result: CallContractResult<types.DIARandomValue>;
    };
    setRound: {
      params: CallContractParams<{ round: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getLastRound: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getRandomValue: {
      params: SignExecuteContractMethodParams<{ round: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    setRound: {
      params: SignExecuteContractMethodParams<{ round: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  MockDIAOracleInstance,
  MockDIAOracleTypes.Fields
> {
  encodeFields(fields: MockDIAOracleTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      types.AllStructs
    );
  }

  at(address: string): MockDIAOracleInstance {
    return new MockDIAOracleInstance(address);
  }

  tests = {
    getLastRound: async (
      params: Omit<
        TestContractParamsWithoutMaps<MockDIAOracleTypes.Fields, never>,
        "args"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getLastRound", params, getContractByCodeHash);
    },
    getRandomValue: async (
      params: TestContractParamsWithoutMaps<
        MockDIAOracleTypes.Fields,
        { round: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<types.DIARandomValue>> => {
      return testMethod(this, "getRandomValue", params, getContractByCodeHash);
    },
    setRound: async (
      params: TestContractParamsWithoutMaps<
        MockDIAOracleTypes.Fields,
        { round: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setRound", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: MockDIAOracleTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const MockDIAOracle = new Factory(
  Contract.fromJson(
    MockDIAOracleContractJson,
    "",
    "4802889283ec3c680c4fa39909691e50e8fd29bd1610365bed6b8dc19042211c",
    types.AllStructs
  )
);
registerContract(MockDIAOracle);

// Use this class to interact with the blockchain
export class MockDIAOracleInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<MockDIAOracleTypes.State> {
    return fetchContractState(MockDIAOracle, this);
  }

  view = {
    getLastRound: async (
      params?: MockDIAOracleTypes.CallMethodParams<"getLastRound">
    ): Promise<MockDIAOracleTypes.CallMethodResult<"getLastRound">> => {
      return callMethod(
        MockDIAOracle,
        this,
        "getLastRound",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRandomValue: async (
      params: MockDIAOracleTypes.CallMethodParams<"getRandomValue">
    ): Promise<MockDIAOracleTypes.CallMethodResult<"getRandomValue">> => {
      return callMethod(
        MockDIAOracle,
        this,
        "getRandomValue",
        params,
        getContractByCodeHash
      );
    },
    setRound: async (
      params: MockDIAOracleTypes.CallMethodParams<"setRound">
    ): Promise<MockDIAOracleTypes.CallMethodResult<"setRound">> => {
      return callMethod(
        MockDIAOracle,
        this,
        "setRound",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getLastRound: async (
      params: MockDIAOracleTypes.SignExecuteMethodParams<"getLastRound">
    ): Promise<MockDIAOracleTypes.SignExecuteMethodResult<"getLastRound">> => {
      return signExecuteMethod(MockDIAOracle, this, "getLastRound", params);
    },
    getRandomValue: async (
      params: MockDIAOracleTypes.SignExecuteMethodParams<"getRandomValue">
    ): Promise<
      MockDIAOracleTypes.SignExecuteMethodResult<"getRandomValue">
    > => {
      return signExecuteMethod(MockDIAOracle, this, "getRandomValue", params);
    },
    setRound: async (
      params: MockDIAOracleTypes.SignExecuteMethodParams<"setRound">
    ): Promise<MockDIAOracleTypes.SignExecuteMethodResult<"setRound">> => {
      return signExecuteMethod(MockDIAOracle, this, "setRound", params);
    },
  };

  async multicall<Calls extends MockDIAOracleTypes.MultiCallParams>(
    calls: Calls
  ): Promise<MockDIAOracleTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends MockDIAOracleTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<MockDIAOracleTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | MockDIAOracleTypes.MultiCallParams
      | MockDIAOracleTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      MockDIAOracle,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
